# Generated by Django 2.2.4 on 2019-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190910_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
