# Generated by Django 2.2.4 on 2019-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_classic',
            field=models.BooleanField(default=False, verbose_name='是否经典'),
        ),
    ]
