# Generated by Django 2.2.4 on 2019-09-10 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComment',
            new_name='CourseComment',
        ),
    ]
