# Generated by Django 2.2.4 on 2019-09-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
