# Generated by Django 2.2.4 on 2019-09-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='defult.jpg', upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
