# Generated by Django 2.2.4 on 2019-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190910_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='media/org/%Y/%m', verbose_name='logo'),
        ),
    ]
