# Generated by Django 2.2.4 on 2019-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190910_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='media/techter/%Y/%m', verbose_name='头像'),
        ),
    ]
