# Generated by Django 2.2.4 on 2019-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20190919_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='就职公司'),
        ),
    ]
